--
-- Initialization data for the PIM module
--
-- @version $Id: drop_schema.sql,v 1.1.1.1 2008-03-20 21:38:29 stefano_fornari Exp $
--

-- drop table if exists borqs_pim_contact_photo        ;
-- drop table if exists borqs_pim_contact_item         ;
-- drop table if exists borqs_pim_address              ;
-- drop table if exists borqs_pim_contact_account      ;
-- drop table if exists borqs_pim_contact              ;
-- drop table if exists borqs_pim_calendar_exception   ;
-- drop table if exists borqs_pim_calendar             ;
-- drop table if exists borqs_pim_listener_registry    ;
-- drop table if exists borqs_push_listener_registry   ;
-- drop table if exists borqs_pim_note                 ;
-- drop table if exists borqs_file_data_object_property;
-- drop table if exists borqs_file_data_object         ;
-- drop table if exists borqs_user_sync_version        ;
-- DROP TRIGGER if exists borqs_contact_update         ;
-- DROP TRIGGER if exists borqs_contact_insert         ;
-- DROP TRIGGER if exists borqs_contact_delete         ;