/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.sync.avro;

@SuppressWarnings("all")
public interface IAccountSyncService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"IAccountSyncService\",\"namespace\":\"com.borqs.sync.avro\",\"types\":[],\"messages\":{\"syncFromAccount\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"since\",\"type\":\"long\"},{\"name\":\"to\",\"type\":\"long\"}],\"response\":\"null\"},\"syncToAccount\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"since\",\"type\":\"long\"},{\"name\":\"to\",\"type\":\"long\"}],\"response\":\"null\"}}}");
  java.lang.Void syncFromAccount(java.lang.CharSequence userId, long since, long to) throws org.apache.avro.AvroRemoteException;
  java.lang.Void syncToAccount(java.lang.CharSequence userId, long since, long to) throws org.apache.avro.AvroRemoteException;
}
