/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.sync.server.framework.services.rpc;

@SuppressWarnings("all")
public interface ITestAvroService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"ITestAvroService\",\"namespace\":\"com.borqs.sync.server.services.rpc\",\"types\":[],\"messages\":{\"foo\":{\"request\":[{\"name\":\"input\",\"type\":\"string\"}],\"response\":\"string\"}}}");
  java.lang.CharSequence foo(java.lang.CharSequence input) throws org.apache.avro.AvroRemoteException;
}
