/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.sync.avro.contactchange;

@SuppressWarnings("all")
public interface IContactChangeProvider {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"IContactChangeProvider\",\"namespace\":\"com.borqs.sync.avro.contactchange\",\"types\":[],\"messages\":{\"getChangeCount\":{\"request\":[{\"name\":\"uid\",\"type\":\"string\"},{\"name\":\"lastsync\",\"type\":\"long\"},{\"name\":\"deviceId\",\"type\":\"string\"}],\"response\":\"string\"},\"getChangedDetail\":{\"request\":[{\"name\":\"uid\",\"type\":\"string\"},{\"name\":\"lastsync\",\"type\":\"long\"},{\"name\":\"deviceId\",\"type\":\"string\"}],\"response\":\"string\"},\"getContact\":{\"request\":[{\"name\":\"uid\",\"type\":\"string\"},{\"name\":\"syncsource\",\"type\":\"string\"},{\"name\":\"luid\",\"type\":\"string\"},{\"name\":\"deviceId\",\"type\":\"string\"}],\"response\":\"string\"}}}");
  java.lang.CharSequence getChangeCount(java.lang.CharSequence uid, long lastsync, java.lang.CharSequence deviceId) throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence getChangedDetail(java.lang.CharSequence uid, long lastsync, java.lang.CharSequence deviceId) throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence getContact(java.lang.CharSequence uid, java.lang.CharSequence syncsource, java.lang.CharSequence luid, java.lang.CharSequence deviceId) throws org.apache.avro.AvroRemoteException;
}
